### AUTH CS
POST https://api.test.cambioseguro.com/api/v1.1/auth/google
Content-Type: application/json

{
    "code": "4/0AX4XfWiLFPQsdJQ96tBhx-NG0x6XC-pH9AlrW9SIhWaPBJ1zgERlkTcVawI55X_TtA_iyw",
    "authuser": "1",
    "prompt": "none",
    "scope": "email https://www.googleapis.com/auth/userinfo.email openid"
}


### GENERAR TOKEN
POST http://localhost:3000/api/v1/auth/google
Content-Type: application/json

{
    "code": "4%2F0AX4XfWihacMTWojywFzxaeh_s46XJSFmxxlbcbqdAFm5Nv-RDA9WCg4Xz0dg0Auky9wT6g"
}

### GENERAR TOKEN
GET http://localhost:3000/api/v1/user/me
Authorization: Bearer ya29.a0ARrdaM8q5PszIzOTDcc0YAr5tKMopTOAmydU9pBCSHndFO6fAAhEz6SfxawnBa1xUwcADJrnBfwUxudzyqMwdznNS6akz7qv_ho01LXzUYSvs7Fz-eukSPoNbxVABpicFvxQ9YKJxdRGs7wzZIzsmTYcCYQt
Content-Type: application/json

### LISTA DE MENSAJES GMAIL
GET http://localhost:3000/api/v1/user/messages?rows=20&page=
Authorization: Bearer ya29.a0ARrdaM8q5PszIzOTDcc0YAr5tKMopTOAmydU9pBCSHndFO6fAAhEz6SfxawnBa1xUwcADJrnBfwUxudzyqMwdznNS6akz7qv_ho01LXzUYSvs7Fz-eukSPoNbxVABpicFvxQ9YKJxdRGs7wzZIzsmTYcCYQt
Content-Type: application/json


### PERFIL GMAIL
GET https://www.googleapis.com/userinfo/v2/me?access_token=ya29.a0ARrdaM9RBYLi4hK1vyXzaLT5ARKNHgzXyiL9VRrcgpnjxKuiFzlm6X35hpjUo1_w5QSPIyJGHstP3_GPfoMYo0-EkmhkQu8pV2diiElTu2cN7brnlqTj7c9Y2vseJ0w7N7AUWq7E1xBz86ebKf75mktiiQ4Tbg
Content-Type: application/json

### MENSAJES BY ID GMAIL
GET http://localhost:3000/api/v1/user/messages/1813fdc3b5873af8
Content-Type: application/json
Authorization: Bearer ya29.a0ARrdaM8q5PszIzOTDcc0YAr5tKMopTOAmydU9pBCSHndFO6fAAhEz6SfxawnBa1xUwcADJrnBfwUxudzyqMwdznNS6akz7qv_ho01LXzUYSvs7Fz-eukSPoNbxVABpicFvxQ9YKJxdRGs7wzZIzsmTYcCYQt

### LISTA DE MENSAJES GMAIL
GET https://www.googleapis.com/gmail/v1/users/me/messages
Content-Type: application/json
Authorization: Bearer ya29.a0ARrdaM8q5PszIzOTDcc0YAr5tKMopTOAmydU9pBCSHndFO6fAAhEz6SfxawnBa1xUwcADJrnBfwUxudzyqMwdznNS6akz7qv_ho01LXzUYSvs7Fz-eukSPoNbxVABpicFvxQ9YKJxdRGs7wzZIzsmTYcCYQt
X-Goog-AuthUser: 0